### PR TITLE
Fix welcome message

### PR DESCRIPTION
**Pull request by erikroyall**
Fix your code thx

### CODE REVIEW

**Comment by ralt** [comment]
Please don't open PRs that break working code.

kthx,

**Comment by ralt** [comment]
For the record, after your PR, she would say "Pleasedon't ask if you can ask" instead of "Please don't ask if you can ask".

**Comment by AmaanC** [comment]
I think you're misreading it, Florian. His change fixes that.

**Comment by ralt** [comment]
I remember fixing that [here](https://github.com/Zirak/SO-ChatBot/commit/0d6924d2908779fd8eacbea2a70aeab23044f8de), so, sup?

**Comment by ralt** [comment]
I have been shown to be wrong, since @Zirak somehow lost my commit.

Reopening.

**Comment by Zirak** [comment]
Thanks for the PR! Could you squash your commits so there'll only be one?

Sorry @ralt, it may have been lost in the browserify merge.

**Comment by erikroyall** [comment]
Done.

**Comment by Zirak** [comment]
Muchas gracias.

**Pull request merged**
