### PR TITLE
generously giving my key for !!weather

### PR DESCRIPTION
**Pull request by cauburtin**
limited to 50,000 req/day http://openweathermap.org/price

### CODE REVIEW

**Comment by Zirak** [comment]
Thanks for the PR!

Does this pose any limitations on you? Since you're just putting this out here random people of the internet can use it. Are you comfortable with that?

Moreover, can openweathermap suddenly invalidate your key for some reason or another? Will we be notified of it?

It's the same concern I had in #234...embedding API keys is annoying in the bot's context right now.

**Comment by cauburtin** [comment]
There are no risk, except a possible abuse of it (I can't monitor usage of the API on their site), it would just be blocked again.

else we can do like Awal's suggestion in your reference

>  just google with site:youtube.com?

**Comment by awalGarg** [comment]
I think it'd be better to add an API key management system to the bot usable only by the bot maintainer backed by a local store (like localStorage/indexedDB/whatever).

Since Caprica essentially functions as a server itself right now, I think this would be harmless. Implementation for the above should take less than 20 loc and would potentially open doors for much a richer set of plugins.

**Comment by SomeKittens** [comment]
Yeah, I wouldn't use keys that were checked into GitHub - they *will* get found & used.

@cauburtin If you generate a new key and send that to rlemon privately, he can enable it as @awalGarg  mentioned.

@rlemon How are you running the bot right now?  Still as a userscript?

**Comment by Zirak** [comment]
This will be part of a `config.js`. Thanks for the PR, but this problem should be solved more widely.

**Pull request closed without merging**
