### PR TITLE
Fix /urban to use HTTPS

### PR DESCRIPTION
**Pull request by Jhawins**
Fixed the urban command, it was a simple http/https issue since it's cors.
Should work now I tested in the sandbox

### CODE REVIEW

**Comment by tentonaxe** [comment]
*"since it's cors."* isn't it jsonp?

**Comment by Jhawins** [comment]
Yes, it's jsonp

**Comment by rlemon** [comment]
looks good, but I'll probably have to rebuild master. no telling what kinda shifty Easter eggs you hid in there. 😉

**Comment by Jhawins** [comment]
Smart man.

On Aug 31, 2017 10:59 AM, "Robert Lemon" <notifications@github.com> wrote:

looks good, but I'll probably have to rebuild master. no telling what kinda
shifty Easter eggs you hid in there. 😉

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Zirak/SO-ChatBot/pull/291#issuecomment-326342308>, or mute
the thread

**Comment by Jhawins** [comment]
Rahhh /urban

**Comment by Zirak** [comment]
Sorry I'm a tard! Next time ping me in chat and I'll merge in a sec.

**Pull request merged**
